### ISSUE TITLE
Error using 1.1.0: StateCollectionThread

### ISSUE THREAD

**Issue by assofohdz** [Simsilica/SiO2#3]
Hi

I've updated to 1.1.0 from 1.0.3, and now I am getting this (without changing anything else):

```
Exception in thread "StateCollectionThread" java.lang.NoSuchMethodError: com.simsilica.mathd.Vec3d.set(Lcom/simsilica/mathd/Vec3d;)V
	at com.simsilica.ethereal.NetworkStateListener.stateChanged(NetworkStateListener.java:345)
	at com.simsilica.ethereal.zone.StateCollector.publish(StateCollector.java:184)
	at com.simsilica.ethereal.zone.StateCollector.publishFrame(StateCollector.java:210)
	at com.simsilica.ethereal.zone.StateCollector.collect(StateCollector.java:246)
	at com.simsilica.ethereal.zone.StateCollector$Runner.run(StateCollector.java:301)
```

I can dig out this as well from the logs:

```
20:09:34,476 ERROR [EventBus] Error handling event:AccountEvent{conn=Connection[ id=0, reliable=NioEndpoint[1, java.nio.channels.SocketChannel[connected local=/127.0.0.1:4271 remote=/127.0.0.1:59093]], fast=UdpEndpoint[1, /127.0.0.1:53362] ], playerName=Asser, playerEntity=EntityId[230980]} for type:PlayerLoggedOn  in handler:com.simsilica.event.EventBus$MethodDispatcher@6b185110
java.lang.RuntimeException: Error calling:public void example.net.server.GameSessionHostedService$AccountObserver.onPlayerLoggedOn(example.net.server.AccountEvent) for event:AccountEvent{conn=Connection[ id=0, reliable=NioEndpoint[1, java.nio.channels.SocketChannel[connected local=/127.0.0.1:4271 remote=/127.0.0.1:59093]], fast=UdpEndpoint[1, /127.0.0.1:53362] ], playerName=Asser, playerEntity=EntityId[230980]}
	at com.simsilica.event.EventBus$MethodDispatcher.newEvent(EventBus.java:339) ~[sio2-1.1.0.jar:?]
	at com.simsilica.event.EventBus.deliver(EventBus.java:176) [sio2-1.1.0.jar:?]
	at com.simsilica.event.EventBus.publishEvent(EventBus.java:150) [sio2-1.1.0.jar:?]
	at com.simsilica.event.EventBus.publish(EventBus.java:84) [sio2-1.1.0.jar:?]
	at example.net.server.AccountHostedService$AccountSessionImpl.login(AccountHostedService.java:188) [main/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at com.jme3.network.service.rmi.MethodInfo.invoke(MethodInfo.java:72) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.service.rmi.RmiRegistry$SharedObject.invoke(RmiRegistry.java:359) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.service.rmi.RmiRegistry.invokeLocal(RmiRegistry.java:332) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.service.rmi.RmiRegistry$RmiHandler.call(RmiRegistry.java:370) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.service.rpc.RpcConnection.handleMessage(RpcConnection.java:193) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at com.jme3.network.util.AbstractMessageDelegator.messageReceived(AbstractMessageDelegator.java:304) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.util.AbstractMessageDelegator.messageReceived(AbstractMessageDelegator.java:57) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.base.MessageListenerRegistry.messageReceived(MessageListenerRegistry.java:81) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.base.DefaultServer.dispatch(DefaultServer.java:341) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.base.DefaultServer$Redispatch.messageReceived(DefaultServer.java:674) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.base.DefaultServer$Redispatch.messageReceived(DefaultServer.java:669) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.base.KernelAdapter.dispatch(KernelAdapter.java:187) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.base.KernelAdapter.createAndDispatch(KernelAdapter.java:241) [jme3-networking-3.1.0-stable.jar:3.1-stable]
	at com.jme3.network.base.KernelAdapter.run(KernelAdapter.java:284) [jme3-networking-3.1.0-stable.jar:3.1-stable]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at com.simsilica.event.EventBus$MethodDispatcher.newEvent(EventBus.java:337) ~[sio2-1.1.0.jar:?]
	... 26 more
Caused by: java.lang.NoSuchMethodError: com.simsilica.mathd.Vec3d.set(Lcom/simsilica/mathd/Vec3d;)V
	at com.simsilica.ethereal.NetworkStateListener.setSelf(NetworkStateListener.java:123) ~[sim-ethereal-1.2.1-SNAPSHOT.jar:?]
	at com.simsilica.ethereal.EtherealHost.setConnectionObject(EtherealHost.java:210) ~[sim-ethereal-1.2.1-SNAPSHOT.jar:?]
	at example.net.server.GameSessionHostedService.startHostingOnConnection(GameSessionHostedService.java:173) ~[main/:?]
	at example.net.server.GameSessionHostedService$AccountObserver.onPlayerLoggedOn(GameSessionHostedService.java:218) ~[main/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at com.simsilica.event.EventBus$MethodDispatcher.newEvent(EventBus.java:337) ~[sio2-1.1.0.jar:?]
	... 26 more
```

I have this in my build.gradle:

```
apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'groovy'

mainClassName='example.Main'

repositories {
    mavenLocal()
    jcenter()
    maven { url "https://jitpack.io" }
    maven { url "https://oss.sonatype.org/content/repositories/snapshots"}
}

ext.jmeVersion = "[3.1,)" 

project(":assets") {
    apply plugin: "java"
    
    buildDir = rootProject.file("build/assets")
    
    sourceSets {
        main {
            resources {
                srcDir '.'
            }
        }
    }    
}


dependencies {
 
    // Need at least basic JME
    compile "org.jmonkeyengine:jme3-core:$jmeVersion"
    compile "org.jmonkeyengine:jme3-desktop:$jmeVersion"
    compile "org.jmonkeyengine:jme3-lwjgl:$jmeVersion"
 
    // We definitely want a UI
    //compile "com.simsilica:lemur:[1.8,)"
    compile "com.simsilica:lemur:1.9.1-SNAPSHOT"
    //compile "com.simsilica:lemur-proto:[1.6,)"
    compile "com.simsilica:lemur-proto:1.7.2-SNAPSHOT"

    // And our base code for sim-etheral, SiO2, etc.
    // (many of these need to be built locally and 'gradle install'ed as of this writing)
    compile "com.simsilica:sio2:1.1.0"
    compile "com.simsilica:sim-math:1.1.1"
    //compile "com.simsilica:sim-ethereal:[1.1,)"    
    compile "com.simsilica:sim-ethereal:1.2.1-SNAPSHOT"

    //Mapeditor format support
    compile 'org.mapeditor:libtiled:0.17-SNAPSHOT'
    // Standard utility stuff
    compile 'com.google.guava:guava:19.0'
    compile 'org.slf4j:slf4j-api:1.7.13'
    runtime 'org.apache.logging.log4j:log4j-slf4j-impl:2.5'
    
    //HSQLDB
    runtime 'org.hsqldb:hsqldb:2.3.4'
    
    //Groovy
    compile 'org.codehaus.groovy:groovy-all:2.4.7'
    
    runtime project(':assets')    
    
    compile 'junit:junit:4.12'
}

task wrapper(type: Wrapper) {
}

/*
This actually exits immediately since there is no standard input stream
task runServer(type: JavaExec) {
    classpath sourceSets.main.runtimeClasspath
    main = "example.net.server.GameServer"
    jvmArgs '-Dlog4j.configurationFile=server-log4j2.xml'
}
*/

// Create a custom server start script in the distribution
task serverStartScript(type: CreateStartScripts) {
    mainClassName = "example.net.server.GameServer"
    applicationName = "server"
    outputDir = new File(project.buildDir, 'scripts')
    classpath = jar.outputs.files + project.configurations.runtime
    defaultJvmOpts = ['-Dlog4j.configurationFile=server-log4j2.xml']
}


/*applicationDistribution.into("bin") {
    from(serverStartScript)
    fileMode = 0755
}*/

// I think this is ultimately clearer than the above
distributions {
    main {
        contents {
            from(serverStartScript) {
                into "bin"
            }
        }
    }
}

// Either way we end up with dupes if we don't do this
distZip {
    duplicatesStrategy = 'exclude'
}
```

Can you help me?

Kind regards,
Asser

**Comment by pspeed42** [comment]
I think this was a sim-math dependency issue?  Is this still an open issue or did you resolve it?

...sorry I'm only seeing this almost a year later.

Edit: also note that this is associated with the wrong project, I think.

**Comment by assofohdz** [comment]
I think this was my fix. Anyway, I dont have the issue anymore:

`    compile 'com.github.Simsilica:SimEthereal:-SNAPSHOT' //There is an unreleased commit that we need`

**Comment by pspeed42** [comment]
Glad you figured it out.  There must be some version mismatch in the
Sim-math references that will get fixed the next time I push a release of
everything I guess.  Sorry for the trouble.

**Comment by assofohdz** [comment]
No trouble. Make no mistake, there's quite a few out there in the community that genuinely appreciates all the work you do with these opensource libraries.

**Comment by pspeed42** [comment]
I'm about to do a big push of releasing new baselines of "everything"... so I will leave this open for a bit longer.

**Comment by pspeed42** [comment]
I think this is resolved if building with the latest versions.  Reopen if the issue persists.
